version: '3.2'
services:
  fluentd:
    image: custom-fluentd:10
    restart: always
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /nfs/esbpv:/var/log/fluent/access
      - ./fluentd/poslog:/home
    depends_on:
      - 'elasticsearch'
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    restart: always
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - node.name=elasticsearch 
      - node.data=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/data/elastic-stack-ca.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/data/elastic-stack-ca.p12
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/data/elastic-stack-ca.p12
      - ELASTIC_PASSWORD=cicduser
     # - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/kibana/data:/usr/share/elasticsearch/data
      - /data/kibana/logs:/usr/share/elasticsearch/logs
   #   - ./config:/usr/share/elasticsearch/config
   #   - /data/kiabna/cert_els:/etc/cert
    ports: 
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    restart: always
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["https://elasticsearch:9200"]
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/etc/cert/kibana.crt
      - SERVER_SSL_KEY=/etc/cert/kibana.key
      - SERVER_SSL_PASSWORD=sleader
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=cicduser
    volumes:
      - /data/kibana/cert:/etc/cert
     # - ./kibana_config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    #  - "6379:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

volumes:
  data01:
    driver: local

networks:
  elastic:
    external: true
    
